<a href="https://colab.research.google.com/github/1830668NabilahOshin/Numerical-methods-and-Neural-Network-Labwork/blob/main/1830668_Mid_LabAssignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Import**

In [ ]:
#Nabilah Tabassum Oshin
#ID- 1830668

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.io as sio

**=>Loading .mat data into 2 variables**

In [ ]:
matdata = sio.loadmat('mnist_train.mat')
digits = matdata['digits']
labels = matdata['labels']

print('the digits matrix shape from mat file :', digits.shape)
print('the labels matrix shape from mat file :', labels.shape)


the digits matrix shape from mat file : (784, 60000)
the labels matrix shape from mat file : (1, 60000)


**=>Taking the first 10000 digits as a dataset**


In [ ]:
data = digits[:,0:10000]
print(data.shape)
row, col = np.shape(data)

(784, 10000)


**=> Storing random indexes of data columns(digits)**

In [ ]:
randidx = np.random.permutation(col)
print(randidx)

[9624 9835 7215 ... 1800 3044 1493]


**=> Declaring group no.**

In [ ]:
k=10

**=> Initializing centroids and groups**

In [ ]:
centroids = np.zeros((row, k))

for i in range(k):
  centroids[:,i] = data[:,randidx[i]]

print('centroids shape:',centroids.shape)

group = np.zeros(col)-1
print(group)

centroids shape: (784, 10)
[-1. -1. -1. ... -1. -1. -1.]


**=> Simple clustering for N=10000**

In [ ]:
for i in range(10000):
    distarr = np.zeros(k)
    for j in range(k):
        distarr[j] = np.sqrt(np.dot((data[:,i]- centroids[:,j]) , (data[:,i]- centroids[:,j])))

    group[i] = np.argmin(distarr)


print('group:', group)

for l in range(k):
  centroids[:,l]= np.mean(data[:,group==l], axis=1)


print('centroids:')
print(centroids)



group: [4. 7. 1. ... 9. 6. 3.]
centroids:
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


**Evaluate clustering using J**