<a href="https://colab.research.google.com/github/1830668NabilahOshin/Numerical-methods-and-Neural-Network-Labwork/blob/main/_LabAssignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:


#Answer 1

import numpy as np
a = np.random.randint(low=1, high=10, size=(5,10))

print(a)

print(a[1, :].sum())

print(a[1, :].mean())

[[5 5 9 7 1 4 6 4 7 4]
 [9 5 2 2 4 8 5 1 8 6]
 [8 8 8 9 7 4 2 5 5 4]
 [8 8 3 5 3 1 7 5 2 9]
 [1 3 8 7 1 3 2 3 6 4]]
50
5.0


In [ ]:
#Answer 2

a=np.random.randint(low=1, high=10, size=(5,10))
print(a)

for row in a:
  print(row.sum())


for row in a:
  print(row.mean())

[[9 5 2 8 5 1 7 9 5 3]
 [3 8 2 1 7 4 7 7 2 2]
 [8 6 6 3 6 5 9 1 1 3]
 [9 2 4 1 4 2 1 1 4 7]
 [4 6 2 5 5 7 1 9 8 1]]
54
43
48
35
48
5.4
4.3
4.8
3.5
4.8


In [ ]:
#Answer 3

v=np.random.randint(low=1, high=10, size=(20,1))
print(v)

print(v.sum() / v.size)



[[9]
 [6]
 [4]
 [3]
 [9]
 [9]
 [4]
 [7]
 [3]
 [6]
 [2]
 [3]
 [1]
 [2]
 [2]
 [3]
 [6]
 [8]
 [3]
 [1]]
4.55


In [ ]:
#Answer 5

a= np.array([1,4,9,16,25])
print(a)

evenarray = []
for element in a:
    if element%2 == 0:
      evenarray.append(element)


print(evenarray)


[ 1  4  9 16 25]
[4, 16]


In [ ]:
#Answer 6

def printeven(a):
  evenarr = []
  for element in a:
    if element%2 == 0:
       evenarr.append(element)

  return(evenarr, len(evenarr))



a= np.array([1,4,9,16,25])
print(a)
printeven(a)


[ 1  4  9 16 25]


([4, 16], 2)