<a href="https://colab.research.google.com/github/1830668NabilahOshin/Numerical-methods-and-Neural-Network-Labwork/blob/main/Lab4_complete_gaussian.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a = np.array([[1,0,2,3],
              [-1,2,2,-3],
              [0,1,1,4],
              [6,2,2,4]])
print(a)

b = np.array([1,-1,2,1])

M = np.column_stack((a,b))
print(M)

for i in range (3):
  pivot = M[i,i]


  for j in range(i+1,4):
    f=M[j,i]/pivot
    M[j] = M[j] - (f*M[i])


print(M)

[[ 1  0  2  3]
 [-1  2  2 -3]
 [ 0  1  1  4]
 [ 6  2  2  4]]
[[ 1  0  2  3  1]
 [-1  2  2 -3 -1]
 [ 0  1  1  4  2]
 [ 6  2  2  4  1]]
[[  1   0   2   3   1]
 [  0   2   4   0   0]
 [  0   0  -1   4   2]
 [  0   0   0 -70 -33]]
